  
name: C/C++ CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build-esp32s2-wroom-at:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: clone esp-idf
      run: |
        commit_str=$(awk '/commit:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
        branch_str=$(awk '/branch:/{print $0}' module_config/module_esp32s2_default/IDF_VERSION)
        git clone -b ${branch_str#*branch:} https://github.com/espressif/esp-idf.git esp-idf
        cd esp-idf
        git checkout ${commit_str#*commit:}
        git submodule update --init --recursive
        cd -
      shell: bash
    - name: Install dependencies
      env:
        IDF_PATH: ${{ github.workspace }}/esp-idf
      run: |
        pip install --upgrade pip
        pip install pyyaml xlrd
        python -m pip install --user -r /home/runner/work/esp-at/esp-at/esp-idf/requirements.txt
    - name: Compiling
      env:
        AT_OTA_TOKEN_ESP32S2_WROOM: ${{ secrets.AT_OTA_TOKEN_ESP32S2_WROOM }}
        AT_OTA_TOKEN_ESP32S2_WROVER: ${{ secrets.AT_OTA_TOKEN_ESP32S2_WROVER }}
        AT_OTA_TOKEN_ESP32S2_SOLO: ${{ secrets.AT_OTA_TOKEN_ESP32S2_SOLO }}
        AT_OTA_TOKEN_ESP32S2_MINI: ${{ secrets.AT_OTA_TOKEN_ESP32S2_MINI }}
      run: |
        cd main
        rm -f at_config.h
        echo -e "#ifndef __AT_CONFIG_H__" >> at_config.h
        echo -e "#define __AT_CONFIG_H__" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROOM \"$AT_OTA_TOKEN_ESP32S2_WROOM\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_WROVER \"$AT_OTA_TOKEN_ESP32S2_WROVER\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_SOLO \"$AT_OTA_TOKEN_ESP32S2_SOLO\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32S2_MINI \"$AT_OTA_TOKEN_ESP32S2_MINI\"" >> at_config.h
        echo -e "#endif" >> at_config.h
        cd -
        
        python ./esp-idf/tools/idf_tools.py --non-interactive install && eval "$(python ./esp-idf/tools/idf_tools.py --non-interactive export)" || exit 1
        python ./esp-idf/tools/idf_tools.py export --prefer-system
        export ESP_AT_PROJECT_PLATFORM=PLATFORM_ESP32S2
        export ESP_AT_MODULE_NAME=WROOM
        export ESP_AT_PROJECT_PATH=$(pwd)
        ./esp-idf/tools/idf.py -DIDF_TARGET=esp32s2 build
        upload_dir=esp32s2-wroom-at
        mkdir -p $upload_dir $upload_dir/bootloader $upload_dir/partition_table $upload_dir/customized_partitions $upload_dir/factory
        cp build/flash_project_args $upload_dir/download.config
        cp build/*.bin $upload_dir/
        cp build/*.elf $upload_dir/
        cp build/*.map $upload_dir/
        cp build/bootloader/*.bin $upload_dir/bootloader/
        cp build/partition_table/*.bin $upload_dir/partition_table/
        cp build/customized_partitions/*.bin $upload_dir/customized_partitions/
        cp build/flasher_args.json $upload_dir/
        cp build/flash_project_args $upload_dir/download.config
        cp build/factory/* $upload_dir/factory
      shell: bash
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: esp32s2-wroom-at
        path: esp32s2-wroom-at
        
  